### ISSUE TITLE
the live demo can't fetch data from your backend-api

### ISSUE THREAD

**Issue by LittleTheFu** [tvillarete/apple-music-js#18]
Hi, the live demo seems not work because it can't fetch data through your backend-api.

**Comment by tvillarete** [comment]
Hey thanks for pointing that out. I recently attempted to change my website to use https, but ran into some technical issues with my server. I then decided to revert back to http, but the certificate had already been installed to some people's machines which causes Chrome to not load "unsafe scripts" (i.e. anything from my http web server).

Check the browser url, and if it's https, change it to http and things should load 👍
