### ISSUE TITLE
TypeError: Cannot read property 'currentTime' of null

### ISSUE THREAD

**Issue by ghost** [tvillarete/apple-music-js#3]
This pops up after a song is finished playing:

TypeError: Cannot read property 'currentTime' of null
(anonymous function)
src/js/components/bar/components/controls/index.js:97
   94 | createTimeInterval() {
   95 |    this.playInterval = setInterval(() => {
   96 |       this.props.updateTime({
   97 |          current: this.audio.currentTime,
   98 |          max: this.audio.duration,
   99 |       });
  100 |    }, 1000);

97 is the one that is making the error happen I believe.

**Comment by tvillarete** [comment]
I believe https://github.com/tvillarete/apple-music-js/pull/4 addresses this issue. Thanks for bringing it up!
