### ISSUE TITLE
Demo is inconsistent with README

### ISSUE THREAD

**Issue by EricWvi** [tvillarete/apple-music-js#56]
Hi, which code base does the demo use?

![image](https://github.com/tvillarete/apple-music-js/assets/49674577/f0206cab-9942-488d-8c0d-2a34ee71c330)

vs.

![image](https://github.com/tvillarete/apple-music-js/assets/49674577/1253d8fd-3888-4090-adad-2c0480bca327)

**Comment by tvillarete** [comment]
Hey @EricWvi, apologies for the confusion here – the demo site was updated several months ago to utilize a new version built using Next.js and Vercel. I never got around to pushing the new code to this repo, but you can still access it here: https://github.com/tvillarete/apple-music-next. Feel free to take a look around!

The new version isn't quite ready to be considered "complete"; I haven't had much time to work on it this year unfortunately. So it'll probably remain incomplete for a while longer unless I happen to have a productive weekend one of these days 😅

**Comment by EricWvi** [comment]
Thanks for reply! 👍
We always have not enough time for hobby projects, right? 🤣
